In [1]:
import pandas as pd
import tables_io
import h5py

In [2]:
data_convert=pd.read_csv('/home/andreia.dourado/data/5sigma_pop_NaN.csv')

In [3]:
data_convert.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', '_healpix_29', 'objectIddp02_object',
       'detect_isPrimarydp02_object', 'coord_radp02_object',
       'coord_decdp02_object', 'u_cModelFluxdp02_object',
       'g_cModelFluxdp02_object', 'r_cModelFluxdp02_object',
       'i_cModelFluxdp02_object', 'z_cModelFluxdp02_object',
       'y_cModelFluxdp02_object', 'u_cModelFluxErrdp02_object',
       'g_cModelFluxErrdp02_object', 'r_cModelFluxErrdp02_object',
       'i_cModelFluxErrdp02_object', 'z_cModelFluxErrdp02_object',
       'y_cModelFluxErrdp02_object', 'Norderdp02_object', 'Dirdp02_object',
       'Npixdp02_object', 'iddp01_test_truth', 'host_galaxydp01_test_truth',
       'radp01_test_truth', 'decdp01_test_truth', 'redshiftdp01_test_truth',
       'is_variabledp01_test_truth', 'is_pointsourcedp01_test_truth',
       'flux_udp01_test_truth', 'flux_gdp01_test_truth',
       'flux_rdp01_test_truth', 'flux_idp01_test_truth',
       'flux_zdp01_test_truth', 'flux_ydp01_test_truth',
       'flux_u_

In [4]:
data_convert = data_convert[['coord_radp02_object','coord_decdp02_object','redshiftdp01_test_truth','mag_u','mag_g','mag_r','mag_i','mag_z','mag_y','magerr_u', 'magerr_g',
       'magerr_r', 'magerr_i', 'magerr_z', 'magerr_y']]
data_convert

coord_radp02_object  coord_decdp02_object  redshiftdp01_test_truth  \
0                 71.430837            -44.627321                 1.026391   
1                 70.659944            -44.623918                 0.892343   
2                 71.035557            -44.620992                 0.781255   
3                 71.214908            -44.621633                 0.523478   
4                 71.313529            -44.627773                 1.304896   
...                     ...                   ...                      ...   
609787            58.600249            -26.822811                 0.306630   
609788            58.641038            -26.800314                 0.706654   
609789            58.689787            -26.788725                 1.489121   
609790            58.701462            -26.779687                 0.833662   
609791            58.564549            -26.802711                 0.940286   

            mag_u      mag_g      mag_r      mag_i      mag_z      mag_y  \
0       74.964297  26.490672  25.920520  25.136450  24.389212  23.641606   
1       26.674136  27.407769  26.254332  25.284254  24.546962  24.605099   
2       28.004136  25.773404  24.410578  23.376798  22.777934  22.542510   
3       23.226723  22.846972  22.069599  21.265850  20.771881  20.601247   
4             NaN  27.182497  26.605260  25.299694  25.847108  23.812302   
...           ...        ...        ...        ...        ...        ...   
609787  26.364427  24.660566  23.294053  22.854730  22.679204  22.387698   
609788  25.553506  27.719590  26.068851  24.816315  25.150922  24.661639   
609789  25.128494  24.028419  23.427147  23.219162  23.098956  23.206158   
609790  75.562642  27.054448  25.745711  24.516733  24.434611  23.554787   
609791        NaN  26.780497  25.135042  23.830273  23.162995  23.170355   

            magerr_u  magerr_g  magerr_r  magerr_i  magerr_z  magerr_y  
0       2.142712e+19  0.236383  0.178401  0.171441  0.179918  0.206195  
1       8.252210e-01  0.510564  0.244495  0.175912  0.167792  0.436265  
2       3.102433e+00  0.133600  0.046336  0.036976  0.041381  0.078272  
3       5.843424e-02  0.013125  0.008479  0.007347  0.009167  0.018929  
4      -8.256937e-01  0.419223  0.302960  0.176664  0.594848  0.219709  
...              ...       ...       ...       ...       ...       ...  
609787  9.036883e-01  0.047238  0.019698  0.024360  0.043714  0.076309  
609788  5.322015e-01  0.968433  0.266478  0.175319  0.541798  0.627633  
609789  3.009836e-01  0.034676  0.024420  0.032871  0.067294  0.165891  
609790  4.335093e+19  0.533547  0.202200  0.102639  0.218588  0.247533  
609791 -8.740624e-01  0.367721  0.122086  0.066529  0.094900  0.187985  

[609792 rows x 15 columns]

In [5]:
columns_map = {
    'redshiftdp01_test_truth': "redshift",
}
data_convert = data_convert.rename(columns=columns_map)

In [6]:
data_convert

coord_radp02_object  coord_decdp02_object  redshift      mag_u  \
0                 71.430837            -44.627321  1.026391  74.964297   
1                 70.659944            -44.623918  0.892343  26.674136   
2                 71.035557            -44.620992  0.781255  28.004136   
3                 71.214908            -44.621633  0.523478  23.226723   
4                 71.313529            -44.627773  1.304896        NaN   
...                     ...                   ...       ...        ...   
609787            58.600249            -26.822811  0.306630  26.364427   
609788            58.641038            -26.800314  0.706654  25.553506   
609789            58.689787            -26.788725  1.489121  25.128494   
609790            58.701462            -26.779687  0.833662  75.562642   
609791            58.564549            -26.802711  0.940286        NaN   

            mag_g      mag_r      mag_i      mag_z      mag_y      magerr_u  \
0       26.490672  25.920520  25.136450  24.389212  23.641606  2.142712e+19   
1       27.407769  26.254332  25.284254  24.546962  24.605099  8.252210e-01   
2       25.773404  24.410578  23.376798  22.777934  22.542510  3.102433e+00   
3       22.846972  22.069599  21.265850  20.771881  20.601247  5.843424e-02   
4       27.182497  26.605260  25.299694  25.847108  23.812302 -8.256937e-01   
...           ...        ...        ...        ...        ...           ...   
609787  24.660566  23.294053  22.854730  22.679204  22.387698  9.036883e-01   
609788  27.719590  26.068851  24.816315  25.150922  24.661639  5.322015e-01   
609789  24.028419  23.427147  23.219162  23.098956  23.206158  3.009836e-01   
609790  27.054448  25.745711  24.516733  24.434611  23.554787  4.335093e+19   
609791  26.780497  25.135042  23.830273  23.162995  23.170355 -8.740624e-01   

        magerr_g  magerr_r  magerr_i  magerr_z  magerr_y  
0       0.236383  0.178401  0.171441  0.179918  0.206195  
1       0.510564  0.244495  0.175912  0.167792  0.436265  
2       0.133600  0.046336  0.036976  0.041381  0.078272  
3       0.013125  0.008479  0.007347  0.009167  0.018929  
4       0.419223  0.302960  0.176664  0.594848  0.219709  
...          ...       ...       ...       ...       ...  
609787  0.047238  0.019698  0.024360  0.043714  0.076309  
609788  0.968433  0.266478  0.175319  0.541798  0.627633  
609789  0.034676  0.024420  0.032871  0.067294  0.165891  
609790  0.533547  0.202200  0.102639  0.218588  0.247533  
609791  0.367721  0.122086  0.066529  0.094900  0.187985  

[609792 rows x 15 columns]

### Cuts

In [ ]:
data_convert = data_convert[data_convert['mag_i']>16]

In [ ]:
data_convert = data_convert[data_convert['mag_i']<24.1]
data_convert

In [ ]:
bands = ['u','g','r','i','z','y']
for i in bands:
    data_convert = data_convert[data_convert[f'mag_{i}']<50]

data_convert

In [ ]:
def mag_histogram(catalog, title='DP0.2'):
    bands = ['u','g', 'r', 'i', 'z','y']
    colors = ['blue', 'green', 'orange','red','purple','gray']
    plt.figure(figsize=(9,13))
    bins = np.linspace(9, 37, 57)
    j=1
    for i, (band, color) in enumerate(zip(bands,colors)):
        plt.subplot(3,2,j)
        plt.hist(catalog[f'mag_{band}'], histtype='stepfilled', bins=bins, label=f'{band} band', alpha = 0.5,
                 edgecolor = "black", color = color)
        #plt.xlim(16,27)
        plt.yscale('log')
        plt.xlabel('mag',fontsize=13)
        plt.ylabel('counts',fontsize=13)
        plt.legend(loc=2)
        plt.grid(True)
        j+=1
    plt.suptitle(title)
    plt.savefig('mag_histogram_training_set.png', format='png')
    plt.show()

In [ ]:
def color_color(catalog):
    bands = ['u', 'g', 'r', 'i', 'z','y']
    i=1
    plt.figure(figsize=(12,12))
    for index in range(len(bands)-2):
        plt.subplot(3,2,i)
        i+=1
        color = catalog[f'mag_{bands[index+1]}']
        next_color = catalog[f'mag_{bands[index+2]}']
        past_color = catalog[f'mag_{bands[index]}']
        plt.hexbin(past_color-color,color-next_color, None, mincnt=1, cmap='turbo', gridsize=[400,200], bins='log')
        plt.xlabel(f'{bands[index+1]}-{bands[index+2]}',fontsize=13)
        plt.ylabel(f'{bands[index]}-{bands[index+1]}',fontsize=13)
        cbar = plt.colorbar()
        #plt.xlim(-5,5)
        #plt.ylim(-5,5)
        plt.savefig('colorColor_training_set.png', format='png')
    plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np 

mag_histogram(data_convert)

In [ ]:
color_color(data_convert)

In [ ]:
def hist(catalog):
    plt.hist(catalog['mag_u'],density=True)
    plt.show()

In [ ]:
hist(data_convert)

### Train file

Selecting the fraction to train

In [7]:
fraction = int(0.7 * len(data_convert))
fraction

426854

In [8]:
training_csv = data_convert.sample(fraction,random_state=40)
training_csv

coord_radp02_object  coord_decdp02_object  redshift      mag_u  \
175135            55.891819            -41.711249  0.310912  25.326758   
309327            54.632760            -31.604070  1.266089  28.753454   
609345            55.991512            -26.915111  0.466051  26.650650   
529865            59.756298            -29.089650  1.790661  23.344095   
606827            57.269545            -27.457888  0.860564  24.215477   
...                     ...                   ...       ...        ...   
535550            61.587860            -29.113775  0.733812  25.666287   
486159            65.344224            -31.883134  0.972941        NaN   
265798            53.294996            -37.729605  0.318172  32.726178   
449621            70.778669            -28.557445  0.596670  28.235131   
163227            50.971692            -43.532458  0.252842  27.634394   

            mag_g      mag_r      mag_i      mag_z      mag_y    magerr_u  \
175135  24.457880  23.675955  23.293092  23.136952  22.877283    0.169672   
309327  26.917623  26.046669  25.232289  25.479438  25.491715    5.180842   
609345  24.305859  22.789107  22.030954  21.616951  21.481308    0.850088   
529865  22.492782  21.360606  20.803230  20.495325  20.373574    0.047162   
606827  24.290900  24.045043  23.366386  23.147100  22.899663    0.079179   
...           ...        ...        ...        ...        ...         ...   
535550  25.279204  24.872648  24.141127  23.933529  23.805939    0.271261   
486159  28.442985  25.855791  25.335608  24.872449  24.548810   -0.548450   
265798  27.334113  25.620836  25.425600  24.667474  24.672301  137.009259   
449621  28.098403  26.032404  25.300006  25.327209  26.179750    2.097082   
163227  26.532344  25.600888  25.409074  26.100411  24.368911    1.183870   

        magerr_g  magerr_r  magerr_i  magerr_z  magerr_y  
175135  0.031917  0.017176  0.022090  0.054958  0.082535  
309327  0.269566  0.142080  0.128143  0.430781  0.869029  
609345  0.038529  0.011252  0.011336  0.014939  0.036101  
529865  0.007674  0.003337  0.003799  0.007254  0.011439  
606827  0.024316  0.021884  0.021110  0.041232  0.075843  
...          ...       ...       ...       ...       ...  
535550  0.063365  0.048855  0.048361  0.119489  0.192181  
486159  1.136570  0.106166  0.114630  0.236258  0.341664  
265798  0.328080  0.077371  0.118910  0.157051  0.336875  
449621  0.557810  0.102793  0.095818  0.268555  1.152595  
163227  0.143726  0.069612  0.113067  0.657833  0.237388  

[426854 rows x 15 columns]

Creating the hdf5 file

In [9]:
train_file_path = '/home/andreia.dourado/TCC/rubin_roman_steps/5sigma/com_populacao/train_file.hdf5'

In [10]:
train_dict_list = training_csv.to_dict(orient='list')

In [11]:
with h5py.File(train_file_path, 'w') as train_file:
    #photometry_group = hdf5_file.create_group('photometry')
    def write_dict(group, data):
        for key, value in data.items():
            if isinstance(value, dict):
                # If the value is a dictionary, create a subgroup and recurse
                subgroup = group.create_group(str(key))
                write_dict(subgroup, value)
            else:
                # Otherwise, write the key-value pair
                group[str(key)] = value

    write_dict(train_file, train_dict_list)

Verifing the file

In [12]:
train_table = tables_io.read(train_file_path, fmt='hdf5')
train_table

OrderedDict([('coord_decdp02_object',
              array([-41.71124872, -31.60406994, -26.91511065, ..., -37.72960514,
                     -28.55744451, -43.53245774])),
             ('coord_radp02_object',
              array([55.89181865, 54.63276047, 55.99151201, ..., 53.29499575,
                     70.77866892, 50.97169203])),
             ('mag_g',
              array([24.45787974, 26.9176228 , 24.30585852, ..., 27.3341133 ,
                     28.09840268, 26.53234358])),
             ('mag_i',
              array([23.2930922 , 25.23228889, 22.03095417, ..., 25.4255998 ,
                     25.30000628, 25.40907405])),
             ('mag_r',
              array([23.67595538, 26.04666908, 22.78910748, ..., 25.62083608,
                     26.03240431, 25.60088778])),
             ('mag_u',
              array([25.32675807, 28.75345374, 26.65064976, ..., 32.72617771,
                     28.23513077, 27.63439435])),
             ('mag_y',
              array([22.87728279, 25

In [13]:
len(train_table['mag_g'])

426854

### Test file

Selecting the fraction to train

In [14]:
validation= data_convert.drop(training_csv.index)
validation

coord_radp02_object  coord_decdp02_object  redshift      mag_u  \
3                 71.214908            -44.621633  0.523478  23.226723   
5                 71.370389            -44.606532  0.895304  25.687499   
7                 71.333458            -44.611040  1.302182  23.820794   
15                71.234262            -44.600420  0.977987  23.081989   
19                71.301155            -44.584287  2.029028  24.529672   
...                     ...                   ...       ...        ...   
609783            58.778274            -26.793919  1.358882  24.215638   
609785            58.632856            -26.835811  1.704935  24.648529   
609786            58.653369            -26.819166  0.573436  26.563087   
609790            58.701462            -26.779687  0.833662  75.562642   
609791            58.564549            -26.802711  0.940286        NaN   

            mag_g      mag_r      mag_i      mag_z      mag_y      magerr_u  \
3       22.846972  22.069599  21.265850  20.771881  20.601247  5.843424e-02   
5       25.801551  25.117560  23.948499  23.650807  23.587091  3.881455e-01   
7       24.081833  23.971763  23.774317  23.435261  23.052480  7.790453e-02   
15      23.202222  22.864887  22.294063  21.900327  21.853418  4.059897e-02   
19      24.153151  23.535773  22.866960  22.155550  21.771755  1.563707e-01   
...           ...        ...        ...        ...        ...           ...   
609783  23.155040  21.904157  21.015100  20.810868  20.739957  1.882912e-01   
609785  24.510035  24.635268  24.700241  26.249212  28.162506  2.332363e-01   
609786  25.914699  25.023808  24.696662  24.175256  23.980099  1.024152e+00   
609790  27.054448  25.745711  24.516733  24.434611  23.554787  4.335093e+19   
609791  26.780497  25.135042  23.830273  23.162995  23.170355 -8.740624e-01   

        magerr_g  magerr_r  magerr_i  magerr_z   magerr_y  
3       0.013125  0.008479  0.007347  0.009167   0.018929  
5       0.167040  0.099416  0.061977  0.110267   0.220121  
7       0.037062  0.037233  0.056680  0.091748   0.129795  
15      0.014162  0.014052  0.015938  0.023398   0.048433  
19      0.036353  0.026235  0.025429  0.027748   0.044671  
...          ...       ...       ...       ...        ...  
609783  0.027801  0.012374  0.008423  0.016649   0.026905  
609785  0.057007  0.087129  0.169737  1.375588  20.150180  
609786  0.161456  0.094292  0.124260  0.168448   0.322729  
609790  0.533547  0.202200  0.102639  0.218588   0.247533  
609791  0.367721  0.122086  0.066529  0.094900   0.187985  

[182938 rows x 15 columns]

Creating the hdf5 file

In [15]:
test_file_path = '/home/andreia.dourado/TCC/rubin_roman_steps/5sigma/com_populacao/test_file.hdf5'

In [16]:
test_dict_list = validation.to_dict(orient='list')

In [17]:
with h5py.File(test_file_path, 'w') as test_file:
    def write_dict(group, data):
        for key, value in data.items():
            if isinstance(value, dict):
                subgroup = group.create_group(str(key))
                write_dict(subgroup, value)
            else:
                group[str(key)] = value

    write_dict(test_file, test_dict_list)

Verifing the file

In [18]:
test_table = tables_io.read(test_file_path, fmt='hdf5')
test_table

OrderedDict([('coord_decdp02_object',
              array([-44.62163299, -44.60653247, -44.61104036, ..., -26.81916648,
                     -26.77968717, -26.80271144])),
             ('coord_radp02_object',
              array([71.21490767, 71.37038852, 71.33345792, ..., 58.65336919,
                     58.70146206, 58.56454906])),
             ('mag_g',
              array([22.84697209, 25.80155132, 24.08183271, ..., 25.91469875,
                     27.05444841, 26.78049678])),
             ('mag_i',
              array([21.26584991, 23.94849943, 23.77431653, ..., 24.69666205,
                     24.5167326 , 23.83027253])),
             ('mag_r',
              array([22.069599  , 25.11756047, 23.97176297, ..., 25.02380763,
                     25.74571084, 25.13504193])),
             ('mag_u',
              array([23.22672291, 25.68749907, 23.82079371, ..., 26.56308656,
                     75.56264199,         nan])),
             ('mag_y',
              array([20.6012471 , 23

In [19]:
len(test_table['mag_g'])

182938